---
- name: Instalando Nginx
  become: yes
  apt:
    name: nginx
    state: present
    
- name: Removendo arquivo Sites-Enabled do NGINX
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-enabled/default
  args:
   warn: no
   
- name: Removendo arquivo Sites-Available do NGINX
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-available/default
  args:
   warn: no

- name: Criando novo arquivo de configração NGINX
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: touch

- name: Inserindo configuração no NGINX
  become: yes
  blockinfile:
      path: /etc/nginx/sites-enabled/default
      marker: ""
      block: |
        server {
          listen      80;
          listen      [::]:80 ipv6only=on;
          root /usr/share/nginx/www;
          index index.html;

          location /grafana/ {
           proxy_pass http://localhost:3000/;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-Server $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }

          location /prometheus/ {
           proxy_pass http://localhost:9090/;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-Server $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }

           location /ne/ {
           proxy_pass http://localhost:91000/metrics;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-Server $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
        }

- name: Removendo arquivo Available Proxy do NGINX
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-available/default
  args:
    warn: no
    
- name: Removendo arquivo index padrão do NGINX
  become: yes
  command:
    cmd: rm -rf /usr/share/nginx/html/index.html
  args:
   warn: no

- name: Copiando página - index.html
  become: yes
  copy:
    src: "{{ role_path }}/files/index.html"
    dest: /usr/share/nginx/html/

- name: Conectando Proxy NGINX
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
  args:
    warn: no

- name: Iniciando NGINX
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
