---
- name: Instalando Nginx
  become: yes
  apt:
    name: nginx
    state: present
    
- name: Removendo arquivo padrão Proxy do NGINX
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-enabled/default
  args:
   warn: no

- name: Criando novo arquivo de configração NGINX
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: touch

- name: Inserindo configuração no NGINX
  become: yes
  blockinfile:
      path: /etc/nginx/sites-enabled/default
      marker: ""
      block: |
        server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html index.htm;
          location /prometheus {
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:9090;
          }
        }
        server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html index.htm;
          location /grafana {
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:3000;
          }
        }
        server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html index.htm;
          location /ne {
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:9100/metrics;
          }
        }

- name: Removendo arquivo Available Proxy do NGINX
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-available/default
  args:
    warn: no
    
- name: Conectando Proxy NGINX
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
  args:
    warn: no

- name: Iniciando NGINX
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
