- name: Instalando pacotes APT necessários
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes

- name: Adicionando chave GPG e APT do Grafana ao repositório 
  shell: |
    curl https://packages.grafana.com/gpg.key | sudo apt-key add -
    add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  args:
    warn: no
  
- name: Adicionando repo do Grafana
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Instalando o Grafana
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: Ativando e iniciando serviço do Grafana
  service:
    name: grafana-server
    enabled: yes
    state: started
    
- name: Iniciando Grafana
  systemd:
    name: grafana-server
    state: started

- name: Habilitando Grafana
  systemd:
    name: grafana-server
    enabled: yes

- name: "Copiando arquivos de configuração do Grafana"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Verificando status 200 do Grafana"
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200
    
- name: Verifica Nginx
  apt:
    name: nginx
    state: present
  notify: Start and Enable Nginx

- name: Cria arquivo do Grafana para Nginx
  copy:
      dest: /etc/nginx/sites-available/default
      mode: 0755
      content: |
        server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html index.htm;

          location /grafana {
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:3000;
          }
        }

- name: Iniciando e Ativando Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    
- name: "Verificando status 200 do Nginx com Grafana"
  uri:
    url: http://127.0.0.1/grafana
    method: GET
    status_code: 200
