- name: Instalando pacotes APT necessários
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes

- name: Adicionando chave GPG e APT do Grafana ao repositório 
  shell: |
    curl https://packages.grafana.com/gpg.key | sudo apt-key add -
    add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  args:
    warn: no
  
- name: Adicionando repo do Grafana
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Instalando o Grafana
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: Ativando e iniciando serviço do Grafana
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: "Copiando arquivos de configuração do Grafana"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Verificando status 200 do Grafana"
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200

- name: Verifica Nginx
  apt:
    name: nginx
    state: present
  notify: Start and Enable Nginx

- name: Cria arquivo do Grafana para Nginx
  copy:
      dest: /etc/nginx/conf.d/grafana.conf
      mode: 0755
      content: |
        server {
          listen 80;
          server_tokens off;
          client_max_body_size 10M;
          server_name _;

          ignore_invalid_headers off;

          if ($host !~* ^(_)$ ) {
              return 444;
          }

          location /grafana {
              send_timeout            600;
              proxy_read_timeout      600;
              proxy_send_timeout      600;
              proxy_connect_timeout   600;
              proxy_redirect          off;
              proxy_set_header        Host $host;
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header        X-Forwarded-Host $server_name;
              proxy_set_header        X-Forwarded-Proto $scheme;
              proxy_pass http://127.0.0.1:3000;
          }
        }
- name: Start grafana
  systemd:
    name: grafana-server
    state: started

- name: Enable grafana
  systemd:
    name: grafana-server
    enabled: yes

- name: Start and Enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
