# Gustavo Kennedy Renkel - 16/06/2022

- name: Instalando pacotes necessários
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes
  retries: 2

- name: Adicionando chave GPG do Grafana
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Adicionado Grafana ao repositório
  retries: 2
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Instalando o Grafana
  retries: 2
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: Habilitando e iniciando o Grafana
  service:
    name: grafana-server
    enabled: yes
    state: started
   
- name: Copiando arquivos de configuração do Grafana
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana
  
- name: Reiniciando Grafana
  systemd:
    name: grafana-server
    state: restarted
    
- name: Aguardando Grafana reiniciar
  wait_for:
    timeout: 3
  delegate_to: localhost

- name: Verificando status 200 do Grafana
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200
    
