# Gustavo Kennedy Renkel - 16/06/2022

- name: Criando grupo para o AlertManager
  group: name="{{groupId}}"
  become: true

- name: Criando usuário para o AlertManager
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Baixando o AlertManager
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copiando executável para pasta BIN
  copy:
    src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Deletando pasta temporária do AlertManager
  file:
    path: '/tmp/alertmanager-{{ version }}.linux-amd64'
    state: absent

- name: Criando diretórios
  file: 
    path: "/data/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Criando diretório de configuração
  file: 
    path: "/etc/alertmanager/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copiando arquivo de configuração
  copy:
    src: "{{ role_path }}/files/alertmanager.yml"
    dest: /etc/alertmanager/alertmanager.yml

- name: Copiando arquivo systemd init
  template:
    src: init.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: systemd_reload

- name: Iniciando serviço do AlertManager
  service:
    name: alertmanager
    state: started
    enabled: yes

- name: Verificando status 200 do AlertManager
  uri:
    url: http://localhost:9093
    method: GET
    status_code: 200
