- name: Criando grupo de usuários para Node_Exporter
  group: name="{{groupId}}"
  become: true

- name: Criando usuário para Node_Exporter
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Instalando o Node_Exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copiando Node_Exporter para pasta BIN
  copy:
    src: "/tmp/node_exporter-{{ version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Removendo pasta temporária
  file:
    path: '/tmp/node_exporter-{{ version }}.linux-amd64'
    state: absent

- name: Copiando arquivo systemd init
  template:
    src: init.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Inicinado o Node_Exporter
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: Verificando status 200 do Node_Exporter
  uri:
    url: http://127.0.0.1:9100/metrics
    method: GET
    status_code: 200
