groups:
- name: alert.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ $labels.instance }} fora do ar"
      description: "A {{ $labels.instance }} do job {{ $labels.job }} está fora do ar mais de 1 minuto."
