- name: Criando grupo de usuário para o Prometheus
  group: name="{{groupId}}"
  become: true

- name: Criando usuário para o Prometheus
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Instalando o Prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copiando Prometheus para pasta BIN
  copy:
    src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Removendo diretório temporário do Prometheus
  file:
    path: '/tmp/prometheus-{{ version }}.linux-amd64'
    state: absent

- name: Criando diretórios em /data
  file: 
    path: "/data/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Criando diretórios em /etc/ para o Prometheus
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copiando arquivos de configuração do Prometheus
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf

- name: Copiando arquivos de Alerta do Prometheus
  copy:
    src: "{{ role_path }}/files/alertrules.yml"
    dest: /etc/prometheus/alert.rules.yml

- name: Copiando arquivo systemd init
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Iniciando o Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
  command:
    cmd: --web.external-url=/prometheus/
  args:
   warn: no
  
- name: Verificando status 200 do Prometheus
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
    
