- name: Criando grupo de usuário para o Prometheus
  group: name="{{groupId}}"
  become: true

- name: Criando usuário para o Prometheus
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present

- name: Instalando o Prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copiando Prometheus para pasta BIN
  copy:
    src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755

- name: Removendo diretório temporário do Prometheus
  file:
    path: '/tmp/prometheus-{{ version }}.linux-amd64'
    state: absent

- name: Criando diretórios em /data
  file: 
    path: "/data/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Criando diretórios em /etc/ para o Prometheus
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755

- name: Copiando arquivos de configuração do Prometheus
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf

- name: Copiando arquivos de Alerta do Prometheus
  copy:
    src: "{{ role_path }}/files/alertrules.yml"
    dest: /etc/prometheus/alert.rules.yml

- name: Copiando arquivo systemd init
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd_reload

- name: Iniciando o Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Verificando status 200 do Prometheus
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
    
- name: Verifica Nginx
  apt:
    name: nginx
    state: present
  notify: Start and Enable Nginx

- name: Cria arquivo do Prometheus para Nginx
  copy:
      dest: /etc/nginx/sites-available/default
      mode: 0755
      content: |
        server {
          listen 80;
          root /usr/share/nginx/html;
          index index.html index.htm;
          location /prometheus {
            proxy_set_header Host $http_host;
            proxy_pass http://127.0.0.1:9090;
          }
        }
- name: Iniciando e Ativando Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    
- name: "Verificando status 200 do Nginx com Prometheus"
  uri:
    url: http://127.0.0.1/prometheus
    method: GET
    status_code: 200
