- name: Reiniciando o Prometheus
  service:
    name: prometheus
    state: restarted
  listen: event_restart_prometheus

- name: Recarregando o systemd
  command: systemctl daemon-reload
  listen: systemd_reload
